### ISSUE TITLE
Training Environment

### ISSUE THREAD

**Issue by shukritolahah** [nocturnalmc/gp2#580]
Perlu ada training environment bagi membantu sesi training secara VC. Basicly sama dengan production, tapi database yang dimasukkan tidak akan digunapakai.

**Comment by nocturnalmc** [comment]
Okay boss. @shukritolahah nak wujudkan staging mcm haritu semula ke? Tp db nak clone dgn db production atau db kosong yg berlainan dgn unstable?

**Comment by shukritolahah** [comment]
kalau db tu berasingan boleh je kan? 

1 db production 
1 db training
1 db dev (unstable)

tp semua kena postgresql

**Comment by nocturnalmc** [comment]
Orait boleh. Aku sediakan environment & dbnya dlu. Tapi db postgresql masih belum berisi. Bila code dah point kat db postgresql baru ada isinya

**Comment by nocturnalmc** [comment]
@shukritolahah boss, training evironment dah ada. DB asing dan kosong. Link di https://girettraining.nocturnal.quest

Nak close issue ke?

**Comment by shukritolahah** [comment]
Korang dh check kan? Dan dia mirror je kan dgn production?

**Comment by nocturnalmc** [comment]
@shukritolahah dari segi code semua mirror dengan production. Tp skrg training environment ada partially code dari unstable sbb haritu base branch dari unstable. Nanti kalau satu point dah decide unstable boleh masuk production training environment ni akan follow production punya code

DB memang semua asing2
- DB Production
- DB Training
- DB Unstable

**Comment by shukritolahah** [comment]
orait closeeed
