### ISSUE TITLE
Fix date format

### ISSUE THREAD

**Issue by shukritolahah** [nocturnalmc/gp2#585]
cari jalan utk force fix kan date semua format ke dd/mm/yyyy

**Comment by nocturnalmc** [comment]
@shukritolahah orait boss. Otw fixing yang ni

**Comment by nocturnalmc** [comment]
@shukritolahah ni pass kat aku xpe boss. Sbb tgh buat ni alang2

**Comment by nocturnalmc** [comment]
@Dvachini din sini. Yang ni assign kat kau

**Comment by nocturnalmc** [comment]
// TODO
- Force dd/mm/yyyy on date input & display date input. Possibly use the new react-datepicker?
