### ISSUE TITLE
Double entry warning mechanism

### ISSUE THREAD

**Issue by shukritolahah** [nocturnalmc/gp2#586]
System prompt user if certain IC already registered under today's date when submitting. Prompt to notify user and confirmation. if yes then continue with double registration. if not then revert back to facility registration page (seperti di bawah). sepatutnya berlaku di setiap fasiliti yang hendak didaftarkan.

![image](https://user-images.githubusercontent.com/115198304/197373731-fe63c833-31af-4221-87a6-f25e1aa03f74.png)

**Comment by c4lyp5o** [comment]
@nocturnalmc dato aku ambil ni lg 1

**Comment by c4lyp5o** [comment]
@shukritolahah @nocturnalmc rs mcm dah selesai yg ni. tlg check. aku tambah sekali confirmation modal untuk semua module kalau nk add data.

**Comment by nocturnalmc** [comment]
Orait dato. Japgi aku check eh. Confirmation modal dato pakai design yg modal hapus x?

**Comment by shukritolahah** [comment]
![image](https://user-images.githubusercontent.com/115198304/198866629-7fada65a-785b-4ad3-903a-89be59cf68cd.png)

maaf zahir batin lambat gais. naisu dah ni. minor2 arrangement boleh buat nnti. syabbas mera betha

**Comment by nocturnalmc** [comment]
// TODO
- Style modal confirmation
- Double register confirmation doesn't work after page refresh or on different device. Watch error msg at console log browser
- Kemaskini broken if you want to submit. Watch error msg at console log browser

@shukritolahah @c4lyp5o aku buka balik issue ni. Ada beberapa error checking x pass lagi

**Comment by c4lyp5o** [comment]
fix baru masuk @nocturnalmc @shukritolahah cuba try test uji

**Comment by nocturnalmc** [comment]
Okay dato @c4lyp5o kacak bergaya. Akan dicuba uji test terai

**Comment by nocturnalmc** [comment]
// TODO

- Style modal confirmation [style: modal confirmation, UserUmumDeleteModal. Broken style still on awas double pt registration](https://github.com/nocturnalmc/gp2/commit/7a9281054645f3edbbf6cd160d03e4e8da212604), [style: fixed awas double registration confirmation](https://github.com/nocturnalmc/gp2/commit/7674bec08667417c3f18bcd0d69d15a64c971630) :heavy_check_mark: **DONE**
- Double register confirmation doesn't work after page refresh or on different device. Watch error msg at console log browser :heavy_check_mark: **DONE**
- Doing kemaskini at pendaftaran broken if you want to submit. Watch error msg at console log browser :heavy_check_mark: **DONE**

@c4lyp5o @shukritolahah aku check semua pass dah. Mohon check semula dan boleh close issue ni inshaAllah

**Comment by c4lyp5o** [comment]
Amiin ya Allah semua dengan izin Allah alhamdulillah syukur

**Comment by nocturnalmc** [comment]
Bump for attention. Nak close issue ke? @c4lyp5o @shukritolahah

**Comment by c4lyp5o** [comment]
@nocturnalmc tggu boss dlu rsnya @shukritolahah. kalau aku boleh dah
