### ISSUE TITLE
Adjustments in table pendaftaran

### ISSUE THREAD

**Issue by shukritolahah** [nocturnalmc/gp2#587]
**A. Adjust table ikut susunan berikut:**

1. Bil
2. Masa Daftar (tarik dari masa pendaftaran yang dibuat)
3. No Pendaftaran (xperlu display kp/kpa/, just bil/tahun. no pendaftaran secara backend perlu panjang. tp better includekan no kod fasiliti dan indicator for pendaftaran di fasiliti mana. akan dan perlu diperhalusi lagi nnti.)
4. Nama Pesakit
5. No. Pengenalan Diri (tukar dari No Kad Pengenalan, bagi kes pendaftaran selain IC)
6. Gugurkan tarikh pendaftaran. Gantikan dengan Status Pesakit ( TOD, SEK, IM, OKU, PES, WE, KKK<< buat mcm label)
7. Kemaskini

**B. Letak disclaimer dkt atas, sekiranya terdapat double pendaftaran, hubungi Admin sistem klinik.**

**C. Letak button "Kemaskini Senarai Pesakit" pada atas table.**

**D. Tetapkan width col dlm table tu. bukti seperti di bawah** 

![image](https://user-images.githubusercontent.com/115198304/197374610-e7c2c9e6-2844-4676-afa1-5d6ba30e7bba.png)

![image](https://user-images.githubusercontent.com/115198304/197374616-21778598-5f88-4786-ad62-3f8cfeca9fb8.png)

**Comment by nocturnalmc** [comment]
@c4lyp5o @Dvachini currently aku tgh work dgn feature ni. Akan link commit bila dah siap utk boss @shukritolahah tgk

**Comment by nocturnalmc** [comment]
@shukritolahah boss, feature semua dah siap. Boleh check kat https://giretunstable.nocturnal.quest

A. Adjust table ikut susunan berikut :heavy_check_mark: 

B. Letak disclaimer dkt atas, sekiranya terdapat double pendaftaran, hubungi Admin sistem klinik. :heavy_check_mark:

C. Letak button "Kemaskini Senarai Pesakit" pada atas table. :heavy_check_mark:

D. Tetapkan width col dlm table tu. bukti seperti di bawah :heavy_check_mark:

**Comment by shukritolahah** [comment]
orait. dah check seperti issue #586. tq
