### ISSUE TITLE
Mechanism delete double registered patient

### ISSUE THREAD

**Issue by shukritolahah** [nocturnalmc/gp2#588]
Admin KP perlu boleh view senarai pesakit di page Umum dan delete senarai pesakit (yang double sahaja or nk open semua?). tapi perlu dapatkan OTP dari email yang didaftarkan.

**Comment by c4lyp5o** [comment]
@nocturnalmc @Dvachini aku amek yg ni

**Comment by nocturnalmc** [comment]
Mantap terus maju

**Comment by c4lyp5o** [comment]
@shukritolahah @nocturnalmc  @Dvachini possibly done. boleh check dkt unstable. pakai user, DR TESTING ARAU. otp akan di send ke janggut dev masa nk delete pt. please test.

**Comment by shukritolahah** [comment]
@c4lyp5o dah check, berfungsi seperti dinyatakan. cuma add ayat yang OTP dah hantar ke email mana boleh?

**Comment by c4lyp5o** [comment]
Ok on

**Comment by nocturnalmc** [comment]
// TODO
- Display send to email mana
- Clear state selection after deletion
- Modal design
- Display semula nama pesakit yang di hapus @ toast

**Comment by nocturnalmc** [comment]
// TODO
- Display send to email mana :heavy_check_mark: **DONE** [feat: OTP display send to email mana](https://github.com/nocturnalmc/gp2/commit/266e20bc264581e399b861a8fc29a5bf652b1dfd)
- Clear state selection after deletion :heavy_check_mark: **DONE** [feat: clear umum state selection after deletion](https://github.com/nocturnalmc/gp2/commit/112b384c4734d5cd397eb33878e4e04dd5acd4e4)
- Delete modal design :heavy_check_mark: **DONE** [style: rework style UserUmumDeleteModal & Kemaskini, refactor: route getotp server.js](https://github.com/nocturnalmc/gp2/commit/74a37a7a80b43489ce68540952aaafb187c0b78c)

// TODO **DONE**
Please review @shukritolahah  @c4lyp5o

**Comment by c4lyp5o** [comment]
@nocturnalmc @shukritolahah ok sgt dah ni. billboard cukup besar dah.

**Comment by shukritolahah** [comment]
![image](https://user-images.githubusercontent.com/115198304/198866745-31977736-7747-46d4-b41f-7cf2a5a881dc.png)

nice dah ada warning. tp estetik xseragam dgn warning sign lain. terlalu lebar. make sure seragam antara warning sign lain jgk.

![image](https://user-images.githubusercontent.com/115198304/198866776-1661fddd-d580-47b7-a4d4-3f3da7d95fe5.png)

rasanya yang ni better kalau ada mcm berapa lama OTP tu valid. mcm OTP bank tu. kalau dah habis waktu kena request lagi. tp aku xsure korang sempat x cari.

**Comment by nocturnalmc** [comment]
@shukritolahah okay boss. Yg ni aku otw buat

**Comment by nocturnalmc** [comment]
// TODO
- Resize UserUmumDeleteModal :heavy_check_mark: **DONE** [style: resize UserUmumDeleteModal] (https://github.com/nocturnalmc/gp2/commit/db08b22e59de884dab4b04c9e5121c35615c5c03)

Resize delete modal kat pengguna siap. Minta check boss @shukritolahah

**Comment by nocturnalmc** [comment]
Bump for attention. Nak close issue ke? @c4lyp5o @shukritolahah

**Comment by c4lyp5o** [comment]
tggu boss @shukritolahah kata apa dlu kot. kalau aku boleh close dah
