### ISSUE TITLE
Different color for pesakit yang telah diisi status pengisian reten

### ISSUE THREAD

**Issue by nocturnalmc** [nocturnalmc/gp2#646]
Feature request from group Gi-Ret Champion

**Comment by Dvachini** [comment]
yg ni aku cadang .belum isi reten terus kebawah .colour kita tukar dekat status reten

**Comment by nocturnalmc** [comment]
// TODO
- Fix umum table width
- Sort status pengisian reten
- Color status pengisian reten

**Comment by nocturnalmc** [comment]
@Xarrenleong @shukritolahah tolong review & close kalau dah berpuas hati

**Comment by Xarrenleong** [comment]
isu telah selesai
